POST http://localhost:5000/pessoas
Content-Type: application/json

{
    "nome": "Josnei, o Violeiro"
}

###

GET http://localhost:5000/pessoas
Content-Type: application/json

###

PUT http://localhost:5000/pessoas/5c95a44c-faf4-4782-bb43-319552595c9d
Content-Type: application/json

{
    "nome": "Gabriel, o Schumann"
}