# Buscar filme por titulo
GET http://localhost:5000/filmes?titulo=Doctor Who

###
# Buscar filme por ID do OMDb
GET http://localhost:5000/filmes?id=tt1877830

###
# Listar todos os filmes armazenados localmente
GET http://localhost:5000/filmes